#!chgops
# Description: This is a simple playbook that runs two commands on the local host.
---
name: demo-playbook
change_id: 0
settings:
  name: "Run commands on the local host"
  vars:
    PAT: '{{ env("PAT", "") }}'
    ansible_connection: "local"
    ansible_python_interpreter: "/usr/bin/python3"
  
tasks:
  - dx.core.bash:
      command: ls -al
      name: "Directory listing in current directory"

  - dx.azure.login:
      command: "login"
      name: "Azure Login with ENV Variables"
    
  - dx.azure.cli:
      command: account list
      name: "Show Azure Account List"
  
