#!chgops
# Description: This is a simple playbook that runs two commands on the local host.
---
name: demo-playbook
change_id: 0
settings:
  name: "Run commands on the local host"
  vars:
    PAT: "{{ env('PAT', '') }}"
    ansible_connection: "local"
    ansible_python_interpreter: "/usr/bin/python3"
  
tasks:
  - dx.azure.login:
      command: task
      name: "this is a demo"
    
  - dx.azure.cli:
      command: task
      name: "another demo"
  
  - dx.core.bash:
      command: ls -al
      name: "yet another demo"