#!chgops
# Description: This is a simple playbook that runs two commands on the local host.
---
name: demo-playbook
change_id: 0
settings:
  name: "Run commands on the local host"
  vars:
    PAT: "{{ env('PAT', '') }}"
    ansible_connection: "local"
    ansible_python_interpreter: "/usr/bin/python3"
  
tasks:
  - name: "Print working directory"
    dx.core.bash: "pwd"
  - name: "List files"
    dx.core.bash: "ls -l"
  - name: Login to Azure
    dx.azure.login:
      auth:
        client_id: "{{ env('AZURE_CLIENT_ID', '') }}"
      
    register: azure_login
  - name: Test az account list
    dx.azure.cli:
      cmd: "account list"
    register: az_account_list    