#!chgops.config
# Description: This is the configuration file for the workspace.
dependencies:
  source: https://deixei.azure.com
  collections:
    - name: dx.azure
      version: 1.0.0

mytags: &mytags
  Owner: demo@deixei.com
  TechOwner: demo@deixei.com
  Ecosystem: MY-DEMO
  Department: MY-DEPARTMENT-123
  OperationalContact: demo@deixei.com
  CostCenter: '22222222'

params:
  time: "{{ current_time() }}"
  client_id: "{{ env_var(name='AZURE_CLIENT_ID') }}"

