#!chgops
# Description: This is a simple playbook that runs two commands on the local host.
---
name: demo-playbook
settings:
  name: "workspace2 - Run commands on the local host"
  vars:
    ansible_connection: "local"
    ansible_python_interpreter: "/usr/bin/python3"


tasks:
  - dx.core.print:
      command: "{{ settings.name }} {# this is a comment #}"
      name: "{{ vars.var1 ~ ' and a string ' ~ vars.var2 }}"

  - dx.core.print:
      command: "{{ vars.var1 }} {{ settings.name | lower }}"
      name: "Vars 1 name"
