#!chgops
# Description: This is a simple playbook that runs two commands on the local host.
---
name: demo-playbook
settings:
  name: "workspace2 - Run commands on the local host"
  vars:
    when_me: "marcio"
    ansible_connection: "local"
    ansible_python_interpreter: "/usr/bin/python3"


tasks:
  - dx.core.print:
      command: "info"
      name: "demo"
      vars:
        resource: "{{ settings | as_json }}"
      when: "{{ settings.vars.when_me == 'marcio' }}"


