#!chgops
# Description: This is a simple playbook that runs two commands on the local host.
---
name: playbook-when
settings:
  name: "workspace2-when"
self:
  sites_name: "my_playbook"
mytags:
  ad1: marcio@deixei.com
tasks:
  - dx.core.print:
      command: "info"
      vars:
        resource: "{{ mytags | as_base64 }}"
      name: "Ecosystem"
      register: eco1

  - dx.core.print:
      command: "debug"
      vars:
        resource: "{{ mytags | as_json }}"
      name: "Tags"
      register: tg1

  - dx.core.print:
      command: "success"
      vars:
        resource: "{{ mytags }}"
      name: "Tags as object"
      register: "tg2"

  - dx.core.print:
      command: "success"
      vars:
        resource: "{{ tg2.stdout }}"
      name: "return from tg1"
      register: "tg3"