#!chgops
# Description: This is a simple playbook that runs two commands on the local host.
---
name: playbook-when
settings:
  name: "workspace2-when"

tasks:
  - dx.core.print:
      command: 
        resource: "{{ azure.tags.Owner }}"
      name: "Ecosystem"
      register: eco1

  - dx.core.print:
      command: 
        resource: "{{ azure.tags }}"
      name: "Tags"
      register: tg1
